### ISSUE TITLE
Duplicate spec names

### ISSUE THREAD

**Issue by 3ikooc** [JTensai/binder#2]
Since there are some duplicate spec names (Holy Priest and Paladin, Restoration Shaman and Druid, Protection Warrior and Paladin, Frost Mage and DK), when I change spec on my paladin it loads my Prot warrior's keybind profile. Is there a way to make the profiles either character-specific or have duplicate specs load a profile with the spec name and the class name in brackets. For example: Protection(Warrior)

**Comment by JTensai** [comment]
This ended up being resolved via pull request. Just name the profile: Paladin-Holy
