### ISSUE TITLE
where is the EDIT button??

### ISSUE THREAD

**Issue by voltuer** [JTensai/binder#3]
I don't have that button, how am I supposed to edit my keys?

![image](https://user-images.githubusercontent.com/197329/64068321-841ded00-cc04-11e9-861c-fa391c0b25a0.png)

**Comment by ebonyfaye** [comment]
you set the keys like you want them and then press update on the profile, make a new profile and then change all the keys the way you need them for proflile two press update again and when you swap it update them ingame,

**Comment by JTensai** [comment]
The edit button was a library plugin that I had found in a different addon and found extremely helpful. At some point one of the WoW updates broke it and the library author never updated it, so I had to remove it.
